baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Afa Lurdes'
theme = "afa"

 [params.logo]
    mobile = "images/afa-logo.png"
    mobile_height = "72px"
    desktop = "images/afa-logo.png"
    desktop_height = "72px"
    alt = "Serif - A Hugo Business Theme"

 [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Montserrat&display=swap'
    heading = "Montserrat"
    base = "Montserrat"

[params.colors]
    primary = "#0046ae"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#efefef"
    grey = "#5c5c5c"
  
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Commissions"
    url = "/commissions"
    weight = 2
  [[menu.main]]
    name = "Noticies"
    url = "/blog"
    weight = 3
  [[menu.main]]
    name = "Contacta'ns"
    url = "/contact"
    weight = 4
