HUGO_VERSION = "0.80.0"
[build]
publish = "public"
command = """\
  git rm --cached themes/blowfish && \
  git submodule add -b main https://github.com/nunocoracao/blowfish.git themes/blowfish && \
  hugo --gc --minify \
  """


